# https://docs.travis-ci.com/user/languages/dart
language: dart
dart:
- stable

before_install:
  - npm install

jobs:
  include:
    - stage: static_analysis
      name: dartfmt
      script: dartfmt --fix -n --set-exit-if-changed .
    - name: dartanalyzer
      script: dartanalyzer --fatal-infos --fatal-warnings .

    - stage: unit_test
      name: build_runner test
      script: pub run build_runner test

    - stage: build_webapp
      name: webdev build & deploy
      script: pub run webdev build
      deploy:
        provider: pages
        "local-dir": build
        "skip-cleanup": true
        "github-token": $GITHUB_TOKEN
        "keep-history": true
        on:
          branch: master

stages:
  - static_analysis
  - unit_test
  - build_webapp

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master

cache:
  directories:
    - $HOME/.pub-cache
    - .dart_tool/build
