name: fvm
homepage: https://github.com/pschiffmann/bachelors-thesis
author: Philipp Schiffmann <philippschiffmann93@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.0
  angular_forms: ^2.0.0
  verbose_regexp: ^1.0.0

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  mockito: ^3.0.0
  test: ^1.3.4
  webdev: ^1.0.0

dependency_overrides:
  verbose_regexp: ^1.0.0
