dart:
- stable
stages:
  - static_analysis:
    - group:
      - dartanalyzer: --fatal-infos --fatal-warnings .
      - command: dartfmt --fix -n --set-exit-if-changed .
  - unit_test:
    - command: pub run build_runner test
  - build_webapp:
    - command: pub run webdev build
cache:
  directories:
    - .dart_tool/build
